### ISSUE TITLE
htacces should be modified

### ISSUE THREAD

**Issue by sherpadawan** [bramley/phplist-plugin-captcha#3]
it should be like that !
<FilesMatch "(index.php|securimage_show.php|dl.php|ut.php|lt.php|download.php|connector.php|api.php)$">

**Comment by bramley** [comment]
I don't understand your comment. This plugin does not have any interest in the .htaccess file in the /lists directory.
I recommend installing securimage in its own directory outside of phplist, so that it is not affected by the phplist .htaccess files.

**Comment by sherpadawan** [comment]
The plugin depends on secureimage which requires some specific acces on file system:
- permissions for securimage directory (which should be set in the captcha plugin
- .htaccess must be modified in order to give access to securimage_show.php file

**Comment by bramley** [comment]
It depends on where you have installed phplist and secureimage. 

With phplist installed in the default location `/lists` and secureimage in `/securimage` then there are no changes to .htaccess necessary. If someone installs in different locations then they are responsible for dealing with any changes for permissions, the plugin cannot do that. Maybe I can update the documentation to point this out.
