### ISSUE TITLE
Project EOL'd - bots defeating securimage

### ISSUE THREAD

**Issue by riker1** [bramley/phplist-plugin-captcha#4]
Just so you know - The author has thrown in the towel on this captcha project. TLDR is that bots can use simple ML or image processing to defeat this captcha. 

https://github.com/dapphp/securimage/issues/66

what about using Google's reCAPTCHA?

**Comment by bramley** [comment]
Yes I had seen that but thanks for reminding me. I will update this plugin's documentation to warn any potential users.

There are other plugins for phplist including google recaptcha that you might want to look at. See https://resources.phplist.com/plugins/start

**Comment by Neustradamus** [comment]
A solution is needed...

**Comment by Neustradamus** [comment]
@bramley: Completed?
